{{- if eq .Values.global.db.type "PGVECTOR" }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
    #startingCSV: {{ .Values.subscription.startingCSV }}
{{- end }}
